/**
 * One-click PDF handoff document for customers.
 * Produces a clean single/multi-page "how your phones work" summary.
 *
 * Uses jsPDF (already in package.json).
 */

import { mergeCallFlowPayload, normalizeAccountRoutes } from './callFlowShape.js'

function slug(name) {
  return String(name || 'customer')
    .replace(/\W+/g, '_')
    .replace(/^_|_$/g, '')
    .toLowerCase() || 'customer'
}

function fmt(val) {
  return String(val || '').trim() || '—'
}

function aaOptionRows(aa) {
  const rows = []
  for (let i = 0; i <= 9; i++) {
    const v = String(aa[`option${i}`] || '').trim()
    if (v) rows.push({ digit: String(i), dest: v })
  }
  return rows
}

export async function exportCallFlowPdf(account) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'letter', orientation: 'portrait' })

  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const ML = 48    // margin left
  const MR = W - 48 // margin right
  const BODY = MR - ML

  const TEAL = [8, 145, 178]
  const INK = [15, 15, 25]
  const MUTED = [100, 110, 125]
  const LINE = [220, 222, 228]
  const TEAL_BG = [236, 254, 255]

  let y = 0

  function newPage() {
    doc.addPage()
    y = 48
    footer()
  }

  function checkY(need = 40) {
    if (y + need > H - 60) newPage()
  }

  function footer() {
    doc.setFontSize(8)
    doc.setTextColor(...MUTED)
    doc.text('Generated by ClearLine · ' + account.name, ML, H - 28)
    doc.text(new Date().toLocaleDateString(), MR, H - 28, { align: 'right' })
    doc.setTextColor(...INK)
  }

  // ── Cover / header ──
  y = 52
  doc.setFillColor(...TEAL)
  doc.rect(ML, y, BODY, 3, 'F')
  y += 12

  doc.setFontSize(22)
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.text(account.name || 'Customer', ML, y + 22)
  y += 30

  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  const subtitle = [
    account.site || '',
    'Call flow guide',
    new Date().toLocaleDateString(),
  ].filter(Boolean).join(' · ')
  doc.text(subtitle, ML, y)
  y += 32

  doc.setFillColor(...LINE)
  doc.rect(ML, y, BODY, 0.5, 'F')
  y += 20

  const routes = normalizeAccountRoutes(account)

  routes.forEach((route, routeIdx) => {
    if (routeIdx > 0) {
      checkY(80)
      doc.setFillColor(...LINE)
      doc.rect(ML, y, BODY, 0.5, 'F')
      y += 20
    }

    const flow = mergeCallFlowPayload(route)
    const aa = flow.autoAttendant || {}
    const night = flow.nightButton || {}
    const hours = flow.hours || {}
    const callFlow = flow.callFlow || {}
    const vm = flow.voicemail || {}
    const mains = (flow.mainNumbers || []).filter(n => String(n.number || '').trim())

    // Route heading
    checkY(60)
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...TEAL)
    doc.text(route.name || `Route ${routeIdx + 1}`, ML, y)
    y += 20

    // Numbers
    if (mains.length) {
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...MUTED)
      doc.text('PHONE NUMBERS', ML, y)
      y += 12
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...INK)
      doc.setFontSize(11)
      mains.forEach(n => {
        checkY(16)
        const label = [n.number, n.label].filter(Boolean).join(' — ')
        doc.text(label, ML + 8, y)
        y += 15
      })
      y += 6
    }

    // Hours
    checkY(40)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...MUTED)
    doc.text('HOURS', ML, y)
    y += 12
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(...INK)
    const hoursLine = (hours.weekdayOpen && hours.weekdayClose)
      ? `${hours.weekdayOpen} – ${hours.weekdayClose}${hours.timezone ? ' (' + hours.timezone + ')' : ''}`
      : '—'
    doc.text(hoursLine, ML + 8, y)
    y += 18

    // Auto attendant
    if (aa.enabled === 'Yes') {
      const opts = aaOptionRows(aa)
      checkY(30 + opts.length * 16)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...MUTED)
      doc.text('AUTO ATTENDANT', ML, y)
      y += 12

      if (aa.greeting) {
        doc.setFont('helvetica', 'italic')
        doc.setFontSize(10)
        doc.setTextColor(...MUTED)
        const wrapped = doc.splitTextToSize(`"${aa.greeting}"`, BODY - 16)
        doc.text(wrapped, ML + 8, y)
        y += wrapped.length * 13 + 4
      }

      if (opts.length) {
        opts.forEach(opt => {
          checkY(16)
          doc.setFillColor(...TEAL_BG)
          doc.roundedRect(ML + 8, y - 10, 22, 14, 3, 3, 'F')
          doc.setFontSize(9)
          doc.setFont('helvetica', 'bold')
          doc.setTextColor(...TEAL)
          doc.text(opt.digit, ML + 19, y, { align: 'center' })
          doc.setFont('helvetica', 'normal')
          doc.setFontSize(11)
          doc.setTextColor(...INK)
          doc.text(opt.dest, ML + 36, y)
          y += 16
        })
      }

      if (aa.timeoutAction) {
        checkY(14)
        doc.setFontSize(9)
        doc.setTextColor(...MUTED)
        doc.text(`Timeout: ${aa.timeoutAction}`, ML + 8, y)
        y += 14
      }
      y += 4
    } else if (callFlow.daytimePath) {
      checkY(30)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...MUTED)
      doc.text('DAYTIME ROUTING', ML, y)
      y += 12
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.setTextColor(...INK)
      const wrapped = doc.splitTextToSize(callFlow.daytimePath, BODY - 16)
      doc.text(wrapped, ML + 8, y)
      y += wrapped.length * 13 + 6
    }

    // Ring groups / queues
    if (callFlow.ringGroups || callFlow.queues) {
      checkY(30)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...MUTED)
      doc.text('RING GROUPS / QUEUES', ML, y)
      y += 12
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.setTextColor(...INK)
      const rg = [callFlow.ringGroups, callFlow.queues].filter(Boolean).join(' · ')
      const wrapped = doc.splitTextToSize(rg, BODY - 16)
      doc.text(wrapped, ML + 8, y)
      y += wrapped.length * 13 + 6
    }

    // After hours
    checkY(30)
    const nightDest = night.destination || callFlow.afterHoursPath || ''
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...MUTED)
    doc.text('AFTER HOURS', ML, y)
    y += 12
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(...INK)
    const afterParts = []
    if (night.whoUses) afterParts.push(`Night button on: ${night.whoUses}`)
    afterParts.push(fmt(nightDest))
    doc.text(afterParts.join(' · '), ML + 8, y)
    y += 18

    // Voicemail
    if (vm.generalMailbox) {
      checkY(20)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...MUTED)
      doc.text('VOICEMAIL', ML, y)
      y += 12
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.setTextColor(...INK)
      doc.text(vm.generalMailbox, ML + 8, y)
      y += 18
    }

    y += 12
  })

  // Account exceptions
  if (account.exceptions) {
    checkY(40)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...MUTED)
    doc.text('ACCOUNT NOTES', ML, y)
    y += 12
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(...INK)
    const wrapped = doc.splitTextToSize(account.exceptions, BODY - 8)
    doc.text(wrapped, ML, y)
    y += wrapped.length * 13 + 8
  }

  footer()

  const filename = `${slug(account.name)}-call-flow-${new Date().toISOString().slice(0, 10)}.pdf`
  doc.save(filename)
}
